controller_list:
 - name: r_arm_controller
   action_ns: follow_joint_trajectory
   default: true
   joints:
     - r_joint1
     - r_joint2
     - r_joint3
     - r_joint4
     - r_joint5
     - r_joint6
     - r_joint7
 
